apiVersion: v1
kind: ConfigMap
metadata:
  name: psql-config
  namespace: wax-contract-api
data:
  SECRET: 09dkdidnmqqqisjsnd77d78eiejdk8
  PGDATA: /var/lib/postgresql/data/pgdata
  POSTGRES_PASSWORD: chocolatechipcookie